### PR TITLE
Removed ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by shreyasbapat**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

After you submit your pull request, **DO NOT click the 'Update Branch' button.

Solves #24 
:wink:

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Done :)

**Comment by sangamcse** [comment]
https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#write-good-commit-messages 😞

**Comment by shreyasbapat** [comment]
Apart from that past tense, I don't think anything is different.
One doesn't have to add a complete link to the commit. Only #<Issue No. > suffices.
If you feel any other thing needs to be changed, mention it rightaway please.

**Comment by sangamcse** [comment]
> One doesn't have to add a complete link to the commit. Only # suffices.

In that case, GitHub gets confused whether you are referencing #issue_number for pull request or issue.

**Comment by sangamcse** [comment]
LGTM 😉 

Also, accept the invitation so that I can assign you before merging it.

**Comment by shreyasbapat** [comment]
All the Pull Requests and Issues have separate No.s 
Check yourself. You can find only one #1 
Anyways, I have changed the rest of the things, I am really not sure what do you expect me to write in commit body.

**Comment by shreyasbapat** [comment]
Thanks!

**Pull request merged**
