### PR TITLE
circularly_linked_list.py Add Circularly Linked List Datastructure

### PR DESCRIPTION
**Pull request by Rishik1504**
Added Circularly Linked List which is a linked list in which the
nodes are connected in the form of a circle. There is no NULL at
the end or starting. If we try to go beyond the last element, we
will return to the first node.

Closes https://github.com/NITSkmOS/Algorithms/issues/33

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

Fixes #{ISSUE_NUMBER}

**By submitting this pull request I confirm I've read and complied with the
below declarations.**

- [x] I have read the [Contribution guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [commit guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#write-good-commit-messages) for this project.
- [x] My code follows the [standard code structure](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#samples-code).
- [x] This pull request has a descriptive title. For example, `{Tag}: Add {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.
- [x] This pull request shall only be reviewed and merged once all the checks passes. No maintainer or supporter shall be obliged to review it before this condition is met.
- [x] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

After you submit your pull request, **DO NOT** click the 'Update Branch' button.

### CODE REVIEW

**Comment by sangamcse** [comment]
Comment on 42d91b717ce61c5d6f8b4f89af997c9e0ad50678, file euclidean_gcd/C/euclidean_gcd.c, line 6.

Missing space before ( in while(  [whitespace/parens] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on 42d91b717ce61c5d6f8b4f89af997c9e0ad50678, file queue/cpp/Queue.h, line 0.

No #ifndef header guard found, suggested CPP variable is: QUEUE_CPP_QUEUE_H_  [build/header_guard] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on 42d91b717ce61c5d6f8b4f89af997c9e0ad50678, file queue/cpp/Queue.h, line 8.

private: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on 42d91b717ce61c5d6f8b4f89af997c9e0ad50678, file queue/cpp/Queue.h, line 10.

public: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on b1d917039f0fd90f2a90989057a05044cd2b2ca4, file euclidean_gcd/C/euclidean_gcd.c, line 6.

Missing space before ( in while(  [whitespace/parens] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on b1d917039f0fd90f2a90989057a05044cd2b2ca4, file queue/cpp/Queue.h, line 0.

No #ifndef header guard found, suggested CPP variable is: QUEUE_CPP_QUEUE_H_  [build/header_guard] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on b1d917039f0fd90f2a90989057a05044cd2b2ca4, file queue/cpp/Queue.h, line 8.

private: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on b1d917039f0fd90f2a90989057a05044cd2b2ca4, file queue/cpp/Queue.h, line 10.

public: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by Rishik1504** [comment]
Could you please tell me how is Travis CI checking my code?
Also how do I check logs on GitMate?

**Comment by sangamcse** [comment]
@Rishik1504, click on details of travis ci

**Comment by sangamcse** [comment]
Comment on a696d2aa518e1ae490716f97b44e6b02861348f0, file euclidean_gcd/C/euclidean_gcd.c, line 6.

Missing space before ( in while(  [whitespace/parens] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on a696d2aa518e1ae490716f97b44e6b02861348f0, file queue/cpp/Queue.h, line 0.

No #ifndef header guard found, suggested CPP variable is: QUEUE_CPP_QUEUE_H_  [build/header_guard] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on a696d2aa518e1ae490716f97b44e6b02861348f0, file queue/cpp/Queue.h, line 8.

private: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on a696d2aa518e1ae490716f97b44e6b02861348f0, file queue/cpp/Queue.h, line 10.

public: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on c73a8823c192e1937b1360283a2ab21936a6c44f, file queue/cpp/Queue.h, line 0.

No #ifndef header guard found, suggested CPP variable is: QUEUE_CPP_QUEUE_H_  [build/header_guard] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on c73a8823c192e1937b1360283a2ab21936a6c44f, file queue/cpp/Queue.h, line 8.

private: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on c73a8823c192e1937b1360283a2ab21936a6c44f, file queue/cpp/Queue.h, line 10.

public: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on c73a8823c192e1937b1360283a2ab21936a6c44f, file euclidean_gcd/C/euclidean_gcd.c, line 6.

Missing space before ( in while(  [whitespace/parens] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Rebase your local repo with the original repo.
Guide: https://github.com/NITSkmOS/Algorithms/blob/master/GIT_BASICS.md#rebasing

**Comment by sangamcse** [comment]
Comment on 14b8e3470336ce1b10afbb7d2da718253efe3161, file queue/cpp/Queue.h, line 0.

No #ifndef header guard found, suggested CPP variable is: QUEUE_CPP_QUEUE_H_  [build/header_guard] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on 14b8e3470336ce1b10afbb7d2da718253efe3161, file queue/cpp/Queue.h, line 8.

private: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on 14b8e3470336ce1b10afbb7d2da718253efe3161, file queue/cpp/Queue.h, line 10.

public: should be indented +1 space inside class Queue  [whitespace/indent] [3]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Comment on 14b8e3470336ce1b10afbb7d2da718253efe3161, file euclidean_gcd/C/euclidean_gcd.c, line 6.

Missing space before ( in while(  [whitespace/parens] [5]

*Origin: CPPLintBear, Section: `all.cpp`.*

**Comment by sangamcse** [comment]
Rebase your local repo which is out of sync with the original repo. 
Get help from https://github.com/NITSkmOS/Algorithms/blob/master/GIT_BASICS.md#rebasing

**Pull request closed without merging**
