### PR TITLE
Optimizing the initial C++ code

### PR DESCRIPTION
**Pull request by SaashaJoshi**
Optimized the initial C++ code.

### CODE REVIEW

**Comment by sangamcse** [comment]
Comment on a9797c684e83facafd838b51f66af99ff5c7f8ab, file bubble_sort/Cpp/bubble_sort.cpp, line 2.

Found C system header after C++ system header. Should be: bubble_sort.h, c system, c++ system, other.  [build/include_order] [4]

*Origin: CPPLintBear, Section: `all.cpplint`.*

**Comment by sangamcse** [comment]
Comment on a9797c684e83facafd838b51f66af99ff5c7f8ab, file bubble_sort/Cpp/bubble_sort.cpp, line 29.

Missing spaces around <<  [whitespace/operators] [3]

*Origin: CPPLintBear, Section: `all.cpplint`.*

**Comment by sangamcse** [comment]
Comment on a9797c684e83facafd838b51f66af99ff5c7f8ab, file bubble_sort/Cpp/bubble_sort.cpp, line 30.

Missing spaces around <<  [whitespace/operators] [3]

*Origin: CPPLintBear, Section: `all.cpplint`.*

**Comment by sangamcse** [comment]
Comment on a9797c684e83facafd838b51f66af99ff5c7f8ab, file bubble_sort/Cpp/bubble_sort.cpp, line 39.

Missing spaces around <<  [whitespace/operators] [3]

*Origin: CPPLintBear, Section: `all.cpplint`.*

**Comment by sangamcse** [comment]
for an opened PR, never use `git commit`. Always use `git commit --amend` which will then open to edit your last commit. And then force push it using `git push -f`.

**Comment by SaashaJoshi** [comment]
Still learning! :) Thanks for the help!

**Comment by sangamcse** [comment]
Feel free to ping on gitter in case you get stuck https://gitter.im/NITSkmOS/algo

**Pull request merged**
