### PR TITLE
Implementation of heap sort in Java

### PR DESCRIPTION
**Pull request by plaidshirtakos**

### CODE REVIEW

**Comment by sangamcse** [comment]
@plaidshirtakos is the issue assigned to you? and did you ask for it?

**Comment by sangamcse** [comment]
PR without assignment

**Comment by plaidshirtakos** [comment]
> @plaidshirtakos is the issue assigned to you? and did you ask for it?

What kind of issue? I haven't opened any.

**Comment by sangamcse** [comment]
The issue for which this PR is opened @plaidshirtakos

**Comment by plaidshirtakos** [comment]
> The issue for which this PR is opened @plaidshirtakos

Yes and that is a fix for PR #207 .

**Pull request closed without merging**
