### PR TITLE
Bubble sort python

### PR DESCRIPTION
**Pull request by Sefiris**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

Fixes #{ISSUE_NUMBER}

**By submitting this pull request I confirm I've read and complied with the
below declarations.**

- [x] I have read the [Contribution guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [X] I have followed the [commit guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#write-good-commit-messages) for this project.
- [x] My code follows the [standard code structure](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#samples-code).
- [ ] This pull request has a descriptive title. For example, `{Tag}: Add {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [X] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.
- [X] This pull request shall only be reviewed and merged once all the checks passes. No maintainer or supporter shall be obliged to review it before this condition is met.
- [ ] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

After you submit your pull request, **DO NOT** click the 'Update Branch' button.

### CODE REVIEW

**Comment by sangamcse** [comment]
Comment on 11393b07606565fa2736ca31a7815937d71ee36d, file bubble_sort/Python/bubble_sort.py, line 35.

Line contains following spacing inconsistencies:
- No newline at EOF.

*Origin: SpaceConsistencyBear, Section: `all.pyjava`.*

The issue can be fixed by applying the following patch:

```diff
--- a/tmp/tmpy65syz4f/bubble_sort/Python/bubble_sort.py
+++ b/tmp/tmpy65syz4f/bubble_sort/Python/bubble_sort.py
@@ -32,4 +32,4 @@
     print(list)
 
 if __name__ == '__main__':
-    main()+    main()
```

**Comment by Sefiris** [comment]
Made a new commit fixing everything listed above, please let me know if anything else needs to be changed. :D

**Comment by sangamcse** [comment]
@Sefiris first thing first get assigned to the issue before actually starting working on it.
Second, someone is already working on https://github.com/NITSkmOS/Algorithms/pull/85. Please respect others time and efforts.

**Comment by Sefiris** [comment]
My apologies I did a quick look through the issues to see if this one was being picked up already, must've glanced over it too quickly.

**Pull request closed without merging**
