### PR TITLE
BubbleSort.Java Add BubbleSort Algorithm Fixes: https://github.com/NI…

### PR DESCRIPTION
**Pull request by flamespt**

### CODE REVIEW

**Comment by sangamcse** [comment]
Rebase your local repo
http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing

**Comment by flamespt** [comment]
I have to rebase my repository and commit ammend again?

**Comment by sangamcse** [comment]
> I have to rebase my repository and commit ammend again?

Yes.
Also, you PR is breaking travis checks. Please fix it

**Comment by flamespt** [comment]
I am having difficulties using that coala stuff...
To resolve this give this issue to someone else cause I have no clue how to proceed

**Pull request closed without merging**
