### PR TITLE
Added binary search algorithm in Python

### LINKED ISSUE #43: [Algo] Binary Search [Python]

### PR DESCRIPTION
**Pull request by swapsha96**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

Fixes #43 

**By submitting this pull request I confirm I've read and complied with the
below declarations.**

- [x] I have read the [Contribution guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [commit guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#write-good-commit-messages) for this project.
- [x] My code follows the [standard code structure](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#samples-code).
- [x] This pull request has a descriptive title. For example, `{Tag}: Add {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.
- [x] This pull request shall only be reviewed and merged once all the checks passes. No maintainer or supporter shall be obliged to review it before this condition is met.
- [x] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

After you submit your pull request, **DO NOT** click the 'Update Branch' button.

### CODE REVIEW

**Comment by swapsha96** [comment]
The output of given example:
```
Index of 5 in the array:  4
Index of 8 in the array:  -1
```

**Comment by swapsha96** [comment]
@sangamcse

**Comment by sangamcse** [comment]
@swapsha96 thanks for your contribution.

Your changes are good. Only 2 things need to be done before merging it:
- You have created 2 commits. Squash them into one. You can check many tutorials online or have a look at https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit
- Commit message is not as per the contribution guidelines that you have ticked st https://github.com/NITSkmOS/Algorithms/pull/69#issue-219221361. 😄

**Comment by sangamcse** [comment]
Do not open multiple PR for one issue. You should have made the correction in this PR also. 
Moving to #74

**Pull request closed without merging**
