### PR TITLE
queue.py  Add Python Queue

### PR DESCRIPTION
**Pull request by SabariVig**
Queue Data Structure Is Implemented In This Program Queue Is A DataStructue Which Follows FIFO ,Which Means First In First Out Which Means Elements Entered First Get Removed First ,Created Using Menu Based

Closes https://github.com/NITSkmOS/Algorithms/issues/55

**By submitting this pull request I confirm I've read and complied with the
below declarations.**

- [x] I have read the [Contribution guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [commit guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#write-good-commit-messages) for this project.
- [x] My code follows the [standard code structure](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#samples-code).
- [x] This pull request has a descriptive title. For example, `{Tag}: Add {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.
- [x] This pull request shall only be reviewed and merged once all the checks passes. No maintainer or supporter shall be obliged to review it before this condition is met.
- [x] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

After you submit your pull request, **DO NOT** click the 'Update Branch' button.

### CODE REVIEW

**Comment by SabariVig** [comment]
Changed 😄

**Comment by sangamcse** [comment]
You just created one extra commit. That makes your total commit equals to 2.
Please Squash both commits into one. http://api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits

**Comment by SabariVig** [comment]
at last done 😀

**Comment by SabariVig** [comment]
Fixed The indentation

**Comment by sangamcse** [comment]
@sangamcse rebase

**Comment by sangamcse** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being rebased automatically. Please **DO NOT** push while rebase is in progress or your changes would be lost permanently :warning:

**Comment by sangamcse** [comment]
Automated rebase with [GitMate.io](https://gitmate.io) was successful! :tada:

**Comment by sangamcse** [comment]
@SabariVig https://github.com/NITSkmOS/Algorithms/pull/84#commitcomment-30734910 fix the commented issue and Update the README. Also, before changing, go through https://github.com/NITSkmOS/Algorithms/blob/master/GIT_BASICS.md#follow-up

**Comment by sangamcse** [comment]
The assignee is no more responding.

**Pull request closed without merging**
