### PR TITLE
Add Maximum SubArray Problem[Python]

### PR DESCRIPTION
**Pull request by halderjoydeep**
[https://github.com/NITSkmOS/Algorithms/issues/215](url)

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

Fixes #{ISSUE_NUMBER}

**By submitting this pull request I confirm I've read and complied with the
below declarations.**

- [x] I have read the [Contribution guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md) and I am confident that my PR reflects them.
- [x] I have followed the [commit guidelines](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#write-good-commit-messages) for this project.
- [x] My code follows the [standard code structure](https://github.com/NITSkmOS/Algorithms/blob/master/CONTRIBUTING.md#samples-code).
- [x] This pull request has a descriptive title. For example, `{Tag}: Add {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.
- [x] This pull request will be closed if I fail to update it even once in a continuous time span of 7 days.
- [x] This pull request shall only be reviewed and merged once all the checks passes. No maintainer or supporter shall be obliged to review it before this condition is met.
- [x] I have mentioned the issue number correctly (with hyperlink) in this pull request description.

After you submit your pull request, **DO NOT** click the 'Update Branch' button.

### CODE REVIEW

**Comment by sangamcse** [comment]
Comment on 9136e99e622faa6b014be106c77e34bf973ba480, file maximum_subarray/max_sub_array.py, line 94.

The code does not comply to PEP8.

*Origin: PEP8Bear, Section: `all.autopep8`.*

The issue can be fixed by applying the following patch:

```diff
--- a/tmp/tmpds7zsk6m/maximum_subarray/max_sub_array.py
+++ b/tmp/tmpds7zsk6m/maximum_subarray/max_sub_array.py
@@ -91,7 +91,8 @@
     else:
         # To be more real-life oriented we start counting from day-1 instead of day-0
 
-        print('Day of Purchase:', l + 1, '\nDay of Selling:', h + 1, '\nProfit:', s)
+        print('Day of Purchase:', l + 1,
+              '\nDay of Selling:', h + 1, '\nProfit:', s)
 
 
 if __name__ == '__main__':
```

**Comment by sangamcse** [comment]
Comment on 9136e99e622faa6b014be106c77e34bf973ba480, file maximum_subarray/max_sub_array.py, line 7.

E501 line too long (81 > 80 characters)

*Origin: PycodestyleBear (E501), Section: `all.autopep8`.*

**Comment by sangamcse** [comment]
Comment on 9136e99e622faa6b014be106c77e34bf973ba480, file maximum_subarray/max_sub_array.py, line 66.

E501 line too long (86 > 80 characters)

*Origin: PycodestyleBear (E501), Section: `all.autopep8`.*

**Comment by sangamcse** [comment]
Comment on 9136e99e622faa6b014be106c77e34bf973ba480, file maximum_subarray/max_sub_array.py, line 92.

E501 line too long (85 > 80 characters)

*Origin: PycodestyleBear (E501), Section: `all.autopep8`.*

**Comment by sangamcse** [comment]
Comment on 9136e99e622faa6b014be106c77e34bf973ba480, file maximum_subarray/max_sub_array.py, line 94.

E501 line too long (84 > 80 characters)

*Origin: PycodestyleBear (E501), Section: `all.autopep8`.*

**Comment by halderjoydeep** [comment]
How to solve this Travis Build issue? I have no idea. A reference is needed,Bhaiya.

**Comment by sangamcse** [comment]
ack 80de1e7

**Pull request merged**
